project_id = "obaiztdbaypwnahdzsls"

[functions.get-gemini-token]
verify_jwt = true

[functions.parse-recipe]
verify_jwt = true

[functions.analyze-vision]
verify_jwt = true

[functions.elevenlabs-tts]
verify_jwt = true
